object fmConfig: TfmConfig
  Left = 0
  Top = 0
  ActiveControl = Edit1
  Caption = 'Configure'
  ClientHeight = 328
  ClientWidth = 632
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  Icon.Data = {
    0000010001002020000001002000A81000001600000028000000200000004000
    0000010020000000000000100000C30E0000C30E00000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFFFFF
    FFFFD1E3FFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADF
    FFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADF
    FFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADF
    FFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFDDEAFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF85AFEDFF4279CBFF5789
    D5FF5185D3FF4E83D1FF6191DAFF4E82D1FF6998DFFF6494DCFF5F90D9FFAACC
    FFFF6E9CE1FF84AEECFFAACCFFFF5487D4FF457CCDFF7FAAEAFF4A7FCFFF578A
    D5FF92B8F3FFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF9DC2F9FF447BCCFF5386
    D3FF4279CBFF2A66BFFF5387D4FF326CC3FF2A66BFFF83ADECFF2662BDFF477D
    CDFF6293DBFF3971C6FF5E8FD9FF467CCDFF437ACCFF96BCF5FF205EBAFF2562
    BDFF9EC2F9FFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF7AA6E7FF3B73C7FF76A2
    E5FF3C74C8FF88B1EEFF4379CBFF5D8ED8FF3D75C9FF90B7F2FF306AC2FF306B
    C2FF5E8FD9FF487ECEFF3F76C9FF467CCDFF5689D5FF8CB4F0FF2662BDFF3971
    C6FF8DB5F1FFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF93BAF4FFA3C6
    FBFF9CC1F8FFAACCFFFF9DC1F8FFA4C7FCFF9EC3F9FFA7C9FDFF95BBF5FFA1C5
    FAFFA1C5FBFF96BCF5FFA6C9FDFF9EC2F9FF95BBF5FFA2C5FBFF96BCF5FF9DC1
    F8FFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFA2C5
    FBFF8BB3EFFFA9CBFEFF91B8F3FF9EC2F9FF9BC0F8FFA3C6FBFF97BDF6FF99BF
    F7FFA7CAFDFFA9CBFFFF8EB6F1FF8DB5F0FFA7CAFEFF95BBF4FF96BCF5FFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF326C
    C3FF6192DBFF77A3E6FF3D75C9FF326CC3FF5588D5FF5A8CD7FF3E76C9FF497F
    CFFF95BBF5FFA8CAFEFF4E82D1FF3F76C9FF85AEECFF3A73C7FF306AC2FFA8CB
    FEFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFA7CAFDFF366F
    C5FFAACCFFFF709EE2FF6D9BE1FF3971C6FF5185D3FF4178CBFF437ACCFF497E
    CEFF447ACCFF96BCF5FF7AA6E7FF6796DDFF719EE2FF6293DBFF5B8DD8FFA9CB
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF5A8C
    D7FF447BCCFF8EB6F1FF3D75C8FF5084D2FF6796DDFF73A0E3FF578AD6FF5C8D
    D8FF467CCDFF81ABEAFF437ACBFF3A73C7FF96BCF5FF4077CAFF5F90DAFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFF79A5E6FFA2C6FBFF709EE2FF719FE3FF497ECEFF90B7F2FF6595
    DDFF78A4E6FF97BDF6FF6897DEFF87B0EDFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFF588AD6FF4F83D1FF4A7FCFFF92B9F3FF487DCEFF6494DCFF2562
    BDFF3871C6FF89B1EEFF3A73C7FF4C81D0FFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFF5A8CD7FF3E75C9FF3871C6FF457BCDFF5C8DD8FF9BC0F7FF2C67
    C0FF437ACBFF6A99DFFF588BD6FF3D75C9FFA9CBFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFF8BB3F0FF96BCF5FF7CA7E8FF96BCF5FF6796DDFF9CC1F8FF7FAA
    EAFF8BB3EFFF85AEECFF96BCF5FF85AEECFFA4C7FCFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFBDD8FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2
    FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2
    FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2
    FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFCEE2FFFFFFFFFFDFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDF0000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000}
  Position = poScreenCenter
  OnShow = FormShow
  TextHeight = 13
  object Label1: TLabel
    Left = 20
    Top = 94
    Width = 52
    Height = 16
    Caption = 'Memory'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label2: TLabel
    Left = 150
    Top = 94
    Width = 73
    Height = 16
    Caption = 'Description'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label3: TLabel
    Left = 64
    Top = 116
    Width = 8
    Height = 16
    Caption = '1'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label4: TLabel
    Left = 582
    Top = 91
    Width = 42
    Height = 16
    Caption = 'Delete'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label5: TLabel
    Left = 64
    Top = 146
    Width = 8
    Height = 16
    Caption = '2'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label6: TLabel
    Left = 64
    Top = 177
    Width = 8
    Height = 16
    Caption = '3'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label7: TLabel
    Left = 64
    Top = 208
    Width = 8
    Height = 16
    Caption = '4'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label8: TLabel
    Left = 64
    Top = 239
    Width = 8
    Height = 16
    Caption = '5'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label9: TLabel
    Left = 64
    Top = 270
    Width = 8
    Height = 16
    Caption = '6'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label10: TLabel
    Left = 20
    Top = 10
    Width = 189
    Height = 16
    Caption = 'MSHV Configuration Manager'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label11: TLabel
    Left = 64
    Top = 32
    Width = 179
    Height = 13
    Caption = '- Configure and adjust MSHV settings'
  end
  object Label12: TLabel
    Left = 64
    Top = 51
    Width = 315
    Height = 13
    Caption = 
      '- Enter a description (example "HF Dxing", "Meteor Scatter", etc' +
      '.)'
  end
  object Label13: TLabel
    Left = 64
    Top = 70
    Width = 55
    Height = 13
    Caption = '- Click Save'
  end
  object Edit1: TEdit
    Tag = 1
    Left = 78
    Top = 112
    Width = 417
    Height = 21
    Hint = 'Enter a description of the configuration'
    AutoSelect = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 0
  end
  object btnSave01: TButton
    Tag = 11
    Left = 501
    Top = 112
    Width = 75
    Height = 25
    Hint = 'Writes the current configuration to Memory 1'
    Caption = 'Save'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 1
    OnClick = btnSaveClick
  end
  object btnDelete01: TButton
    Tag = 21
    Left = 582
    Top = 113
    Width = 33
    Height = 25
    Hint = 'Deletes the saved configuration in Memory 1'
    Caption = 'r'
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Webdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 2
    OnClick = btnDeleteClick
  end
  object Edit2: TEdit
    Tag = 2
    Left = 78
    Top = 143
    Width = 417
    Height = 21
    TabOrder = 3
  end
  object btnSave02: TButton
    Tag = 12
    Left = 501
    Top = 143
    Width = 75
    Height = 25
    Caption = 'Save'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 4
    OnClick = btnSaveClick
  end
  object btnDelete02: TButton
    Tag = 22
    Left = 582
    Top = 144
    Width = 33
    Height = 25
    Caption = 'r'
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Webdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 5
    OnClick = btnDeleteClick
  end
  object Edit3: TEdit
    Tag = 3
    Left = 78
    Top = 174
    Width = 417
    Height = 21
    TabOrder = 6
  end
  object btnSave03: TButton
    Tag = 13
    Left = 501
    Top = 174
    Width = 75
    Height = 25
    Caption = 'Save'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 7
    OnClick = btnSaveClick
  end
  object btnDelete03: TButton
    Tag = 23
    Left = 582
    Top = 175
    Width = 33
    Height = 25
    Caption = 'r'
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Webdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 8
    OnClick = btnDeleteClick
  end
  object Edit4: TEdit
    Tag = 4
    Left = 78
    Top = 205
    Width = 417
    Height = 21
    TabOrder = 9
  end
  object btnSave04: TButton
    Tag = 14
    Left = 501
    Top = 205
    Width = 75
    Height = 25
    Caption = 'Save'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 10
    OnClick = btnSaveClick
  end
  object btnDelete04: TButton
    Tag = 24
    Left = 582
    Top = 206
    Width = 33
    Height = 25
    Caption = 'r'
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Webdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 11
    OnClick = btnDeleteClick
  end
  object Edit5: TEdit
    Tag = 5
    Left = 78
    Top = 236
    Width = 417
    Height = 21
    TabOrder = 12
  end
  object btnSave05: TButton
    Tag = 15
    Left = 501
    Top = 236
    Width = 75
    Height = 25
    Caption = 'Save'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 13
    OnClick = btnSaveClick
  end
  object btnDelete05: TButton
    Tag = 25
    Left = 582
    Top = 237
    Width = 33
    Height = 25
    Caption = 'r'
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Webdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 14
    OnClick = btnDeleteClick
  end
  object Edit6: TEdit
    Tag = 6
    Left = 78
    Top = 267
    Width = 417
    Height = 21
    AutoSelect = False
    TabOrder = 15
  end
  object btnSave06: TButton
    Tag = 16
    Left = 501
    Top = 267
    Width = 75
    Height = 25
    Caption = 'Save'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 16
    OnClick = btnSaveClick
  end
  object btnDelete06: TButton
    Tag = 26
    Left = 582
    Top = 268
    Width = 33
    Height = 25
    Caption = 'r'
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Webdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 17
    OnClick = btnDeleteClick
  end
  object btnConfigClose: TButton
    Left = 280
    Top = 294
    Width = 75
    Height = 25
    Caption = 'Close'
    TabOrder = 18
    OnClick = btnConfigCloseClick
  end
end
