object fmHelp: TfmHelp
  Left = 0
  Top = 0
  VertScrollBar.Visible = False
  Caption = 'Help'
  ClientHeight = 542
  ClientWidth = 506
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  Icon.Data = {
    0000010001002020000001002000A81000001600000028000000200000004000
    0000010020000000000000100000C30E0000C30E00000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFFFFF
    FFFFD1E3FFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADF
    FFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADF
    FFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADF
    FFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFDDEAFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF85AFEDFF4279CBFF5789
    D5FF5185D3FF4E83D1FF6191DAFF4E82D1FF6998DFFF6494DCFF5F90D9FFAACC
    FFFF6E9CE1FF84AEECFFAACCFFFF5487D4FF457CCDFF7FAAEAFF4A7FCFFF578A
    D5FF92B8F3FFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF9DC2F9FF447BCCFF5386
    D3FF4279CBFF2A66BFFF5387D4FF326CC3FF2A66BFFF83ADECFF2662BDFF477D
    CDFF6293DBFF3971C6FF5E8FD9FF467CCDFF437ACCFF96BCF5FF205EBAFF2562
    BDFF9EC2F9FFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF7AA6E7FF3B73C7FF76A2
    E5FF3C74C8FF88B1EEFF4379CBFF5D8ED8FF3D75C9FF90B7F2FF306AC2FF306B
    C2FF5E8FD9FF487ECEFF3F76C9FF467CCDFF5689D5FF8CB4F0FF2662BDFF3971
    C6FF8DB5F1FFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF93BAF4FFA3C6
    FBFF9CC1F8FFAACCFFFF9DC1F8FFA4C7FCFF9EC3F9FFA7C9FDFF95BBF5FFA1C5
    FAFFA1C5FBFF96BCF5FFA6C9FDFF9EC2F9FF95BBF5FFA2C5FBFF96BCF5FF9DC1
    F8FFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFA2C5
    FBFF8BB3EFFFA9CBFEFF91B8F3FF9EC2F9FF9BC0F8FFA3C6FBFF97BDF6FF99BF
    F7FFA7CAFDFFA9CBFFFF8EB6F1FF8DB5F0FFA7CAFEFF95BBF4FF96BCF5FFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF326C
    C3FF6192DBFF77A3E6FF3D75C9FF326CC3FF5588D5FF5A8CD7FF3E76C9FF497F
    CFFF95BBF5FFA8CAFEFF4E82D1FF3F76C9FF85AEECFF3A73C7FF306AC2FFA8CB
    FEFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFA7CAFDFF366F
    C5FFAACCFFFF709EE2FF6D9BE1FF3971C6FF5185D3FF4178CBFF437ACCFF497E
    CEFF447ACCFF96BCF5FF7AA6E7FF6796DDFF719EE2FF6293DBFF5B8DD8FFA9CB
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF5A8C
    D7FF447BCCFF8EB6F1FF3D75C8FF5084D2FF6796DDFF73A0E3FF578AD6FF5C8D
    D8FF467CCDFF81ABEAFF437ACBFF3A73C7FF96BCF5FF4077CAFF5F90DAFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFF79A5E6FFA2C6FBFF709EE2FF719FE3FF497ECEFF90B7F2FF6595
    DDFF78A4E6FF97BDF6FF6897DEFF87B0EDFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFF588AD6FF4F83D1FF4A7FCFFF92B9F3FF487DCEFF6494DCFF2562
    BDFF3871C6FF89B1EEFF3A73C7FF4C81D0FFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFF5A8CD7FF3E75C9FF3871C6FF457BCDFF5C8DD8FF9BC0F7FF2C67
    C0FF437ACBFF6A99DFFF588BD6FF3D75C9FFA9CBFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFF8BB3F0FF96BCF5FF7CA7E8FF96BCF5FF6796DDFF9CC1F8FF7FAA
    EAFF8BB3EFFF85AEECFF96BCF5FF85AEECFFA4C7FCFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFBDD8FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2
    FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2
    FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2
    FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFCEE2FFFFFFFFFFDFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDF0000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000}
  Position = poScreenCenter
  TextHeight = 13
  object btnHelpClose: TButton
    Left = 216
    Top = 509
    Width = 75
    Height = 25
    Caption = 'Close'
    TabOrder = 0
    OnClick = btnHelpCloseClick
  end
  object RichEdit1: TRichEdit
    Left = 9
    Top = 8
    Width = 489
    Height = 489
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    HideScrollBars = False
    Lines.Strings = (
      
        'MSHV CONFIGURATION SWAPPER                                      ' +
        '                    v1.00'
      'by Jim Varney, K6OK'
      ''
      
        'This is a simple program that allows you to store and load up to' +
        ' 6 different MSHV '
      
        'configurations. Each saved configuration includes all of the set' +
        'tings in effect when '
      'saved.'
      ''
      
        'INSTALL.  Run Swapper. Click Setup. Follow the instructions: Ste' +
        'p 1 creates the '
      
        'storage folders on your drive (in {USER}\AppData\Local). Step 2 ' +
        'asks you to '
      'show Swapper where your MSHV folder is.'
      ''
      
        'SAVE A CONFIG. In MSHV, set all desired options. In Swapper, sel' +
        'ect Configuration, '
      
        'write a short description into one of the 6 memory slots.  Click' +
        ' Save.'
      ''
      
        'LOAD A CONFIG. Close MSHV. On the main Swapper screen, click one' +
        ' of the 6 '
      
        'buttons to load that previously saved configuration. Restart MSH' +
        'V.  Hovering your '
      
        'mouse over the button will display your description for that con' +
        'figuration.'
      ''
      
        'NOTE: You must shut down MSHV before loading a saved configurati' +
        'on. '
      ''
      
        'WHY IS SWAPPER SO SMALL?  I did that on purpose because I wanted' +
        ' to be able '
      
        'to tuck it into a screen corner and not use up very much monitor' +
        ' real estate.'
      ''
      'Tested on Windows 10 with MSHV 2.71. -- 73 gud DX!'
      ''
      '')
    ParentFont = False
    ReadOnly = True
    TabOrder = 1
  end
end
