object fmMain: TfmMain
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'MSHV Config Swapper'
  ClientHeight = 89
  ClientWidth = 256
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  Icon.Data = {
    0000010001002020000001002000A81000001600000028000000200000004000
    0000010020000000000000100000C30E0000C30E00000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFFFFF
    FFFFD1E3FFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADF
    FFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADF
    FFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADF
    FFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFCADFFFFFDDEAFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF85AFEDFF4279CBFF5789
    D5FF5185D3FF4E83D1FF6191DAFF4E82D1FF6998DFFF6494DCFF5F90D9FFAACC
    FFFF6E9CE1FF84AEECFFAACCFFFF5487D4FF457CCDFF7FAAEAFF4A7FCFFF578A
    D5FF92B8F3FFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF9DC2F9FF447BCCFF5386
    D3FF4279CBFF2A66BFFF5387D4FF326CC3FF2A66BFFF83ADECFF2662BDFF477D
    CDFF6293DBFF3971C6FF5E8FD9FF467CCDFF437ACCFF96BCF5FF205EBAFF2562
    BDFF9EC2F9FFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF7AA6E7FF3B73C7FF76A2
    E5FF3C74C8FF88B1EEFF4379CBFF5D8ED8FF3D75C9FF90B7F2FF306AC2FF306B
    C2FF5E8FD9FF487ECEFF3F76C9FF467CCDFF5689D5FF8CB4F0FF2662BDFF3971
    C6FF8DB5F1FFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF93BAF4FFA3C6
    FBFF9CC1F8FFAACCFFFF9DC1F8FFA4C7FCFF9EC3F9FFA7C9FDFF95BBF5FFA1C5
    FAFFA1C5FBFF96BCF5FFA6C9FDFF9EC2F9FF95BBF5FFA2C5FBFF96BCF5FF9DC1
    F8FFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFA2C5
    FBFF8BB3EFFFA9CBFEFF91B8F3FF9EC2F9FF9BC0F8FFA3C6FBFF97BDF6FF99BF
    F7FFA7CAFDFFA9CBFFFF8EB6F1FF8DB5F0FFA7CAFEFF95BBF4FF96BCF5FFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF326C
    C3FF6192DBFF77A3E6FF3D75C9FF326CC3FF5588D5FF5A8CD7FF3E76C9FF497F
    CFFF95BBF5FFA8CAFEFF4E82D1FF3F76C9FF85AEECFF3A73C7FF306AC2FFA8CB
    FEFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFA7CAFDFF366F
    C5FFAACCFFFF709EE2FF6D9BE1FF3971C6FF5185D3FF4178CBFF437ACCFF497E
    CEFF447ACCFF96BCF5FF7AA6E7FF6796DDFF719EE2FF6293DBFF5B8DD8FFA9CB
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFF5A8C
    D7FF447BCCFF8EB6F1FF3D75C8FF5084D2FF6796DDFF73A0E3FF578AD6FF5C8D
    D8FF467CCDFF81ABEAFF437ACBFF3A73C7FF96BCF5FF4077CAFF5F90DAFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFF79A5E6FFA2C6FBFF709EE2FF719FE3FF497ECEFF90B7F2FF6595
    DDFF78A4E6FF97BDF6FF6897DEFF87B0EDFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFF588AD6FF4F83D1FF4A7FCFFF92B9F3FF487DCEFF6494DCFF2562
    BDFF3871C6FF89B1EEFF3A73C7FF4C81D0FFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFF5A8CD7FF3E75C9FF3871C6FF457BCDFF5C8DD8FF9BC0F7FF2C67
    C0FF437ACBFF6A99DFFF588BD6FF3D75C9FFA9CBFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFF8BB3F0FF96BCF5FF7CA7E8FF96BCF5FF6796DDFF9CC1F8FF7FAA
    EAFF8BB3EFFF85AEECFF96BCF5FF85AEECFFA4C7FCFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFB4D2FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACC
    FFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFAACCFFFFC8DEFFFFFFFFFFDFFFFF
    FFFFBDD8FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2
    FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2
    FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2
    FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFB4D2FFFFCEE2FFFFFFFFFFDFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDF0000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000}
  Menu = MainMenu1
  Position = poDefault
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  TextHeight = 13
  object Shape1: TShape
    Left = 8
    Top = 24
    Width = 239
    Height = 1
    Pen.Color = clBtnShadow
  end
  object Label1: TLabel
    Left = 92
    Top = 8
    Width = 74
    Height = 13
    Caption = 'M E M O R I E S'
  end
  object btnConfig1: TButton
    Tag = 1
    Left = 8
    Top = 31
    Width = 35
    Height = 25
    Caption = '1'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 0
    TabStop = False
    OnClick = btnMemoryClick
    OnMouseEnter = btnMouseEnter
  end
  object btnConfig2: TButton
    Tag = 2
    Left = 49
    Top = 31
    Width = 35
    Height = 25
    Caption = '2'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 1
    TabStop = False
    OnClick = btnMemoryClick
    OnMouseEnter = btnMouseEnter
  end
  object btnConfig3: TButton
    Tag = 3
    Left = 90
    Top = 31
    Width = 35
    Height = 25
    Caption = '3'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 2
    TabStop = False
    OnClick = btnMemoryClick
    OnMouseEnter = btnMouseEnter
  end
  object btnConfig4: TButton
    Tag = 4
    Left = 131
    Top = 31
    Width = 35
    Height = 25
    Caption = '4'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 3
    TabStop = False
    OnClick = btnMemoryClick
    OnMouseEnter = btnMouseEnter
  end
  object btnConfig5: TButton
    Tag = 5
    Left = 172
    Top = 31
    Width = 35
    Height = 25
    Caption = '5'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 4
    TabStop = False
    OnClick = btnMemoryClick
    OnMouseEnter = btnMouseEnter
  end
  object btnConfig6: TButton
    Tag = 6
    Left = 213
    Top = 31
    Width = 35
    Height = 25
    Caption = '6'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 5
    TabStop = False
    OnClick = btnMemoryClick
    OnMouseEnter = btnMouseEnter
  end
  object panelStatus: TPanel
    Left = 9
    Top = 62
    Width = 239
    Height = 16
    Alignment = taLeftJustify
    BevelOuter = bvLowered
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 6
  end
  object MainMenu1: TMainMenu
    Left = 160
    object menuSetup: TMenuItem
      Caption = 'Setup'
      OnClick = menuSetupClick
    end
    object menuConfig: TMenuItem
      Caption = 'Configure'
      OnClick = menuConfigClick
    end
    object menuHelp: TMenuItem
      Caption = 'Help'
      OnClick = menuHelpClick
    end
  end
end
